### PR TITLE
fix: guard against empty log captures

### LINKED ISSUE #12: TypeError in afterEach when test has no output at all
**problem**
I have a test with no output, then I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'stream')
    at Context.afterEach (node_modules/mocha-suppress-logs/index.js:14:29)
    at process.processImmediate (node:internal/timers:476:21)
```

**workaround**
add `process.stdout.write('')`

**note**
I'm running the tests within webstorm, and they set their own reporter:

```
--reporter /Users/shared/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/232.10203.14/WebStorm.app/Contents/plugins/nodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js
```

I assume they don't write anything to stdout.

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #12

### CODE REVIEW

**Review by dominique-pfister — APPROVED** [review]

**Comment by tripodsan** [comment]
Hi @AleG94 , any chance that we can get this PR merged? thanks.

**Comment by AleG94** [comment]
Hi @tripodsan, unfortunately this pull request only fixes a handful of use cases but it's not a solution that works on every reporter so I reverted back to intercepting console methods instead of stdout and stderr and released 0.5.0. 

Would you mind confirming that it works properly for you as well?

**Comment by tripodsan** [comment]
thank @AleG94  for the fix, it works. but I think the `clone` dependency should not be a dev dependency. now I get:

```
✖ ERROR: Error: Cannot find module 'clone'
Require stack:
- /Users/.../.../node_modules/mocha-suppress-logs/lib/log-capture.js
- /Users/.../.../node_modules/mocha-suppress-logs/index.js
```

**Comment by AleG94** [comment]
Right, 0.5.1 released with the fix!

**Comment by tripodsan** [comment]
thank you for the quick turnaround.

**Pull request closed without merging**
